name: Build Linux x86-64 and execute tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #build and install XP-CMake
    - name: Checkout XP-CMake repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/XP-CMake
        path: xpcmake

    - name: Create build directory for XP-CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/xpcmake/_build -S ${{github.workspace}}/xpcmake

    - name: Build XP-CMake
      run: cmake --build ${{github.workspace}}/xpcmake/_build --config ${{env.BUILD_TYPE}}

    - name: Install XP-CMake
      run: sudo make install
      working-directory: ${{github.workspace}}/xpcmake/_build


    #build and install Std++
    - name: Checkout Std++ repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/StdPlusPlus
        path: stdpp

    - name: Create build directory for Std++
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/stdpp/_build -S ${{github.workspace}}/stdpp

    - name: Build Std++
      run: cmake --build ${{github.workspace}}/stdpp/_build --config ${{env.BUILD_TYPE}}

    - name: Install Std++
      run: sudo make install
      working-directory: ${{github.workspace}}/stdpp/_build



    #build KORG-Tools
    - name: Checkout KORG-Tools repo
      uses: actions/checkout@v4
      with:
        path: korgtools

    - name: Configure build directory for KORG-Tools
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/korgtools/_build -S ${{github.workspace}}/korgtools

    - name: Build KORG-Tools
      run: cmake --build ${{github.workspace}}/korgtools/_build --config ${{env.BUILD_TYPE}}

    #execute tests
    - name: Execute tests
      run: ./_build/tests/tests 1>results.json 2>results-stderr.log
      working-directory: ${{github.workspace}}/korgtools

    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-result-report
        path: ${{github.workspace}}/korgtools/results*

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests
        path: ${{github.workspace}}/korgtools/results.json
        reporter: mocha-json